import hardhat from 'hardhat';
import fs from 'fs';
import path from 'path';

const { ethers } = hardhat;

async function main() {
  const [deployer] = await ethers.getSigners();
  const network = await ethers.provider.getNetwork();
  console.log('Deploying PrivateScratchRegistry');
  console.log('Network:', network.name, network.chainId.toString());
  console.log('Deployer:', deployer.address);

  const Factory = await ethers.getContractFactory('PrivateScratchRegistry');
  const registry = await Factory.deploy();
  await registry.waitForDeployment();
  const address = await registry.getAddress();
  console.log('PrivateScratchRegistry deployed to:', address);

  const deploymentDir = path.join(process.cwd(), 'deployment');
  fs.mkdirSync(deploymentDir, { recursive: true });
  const deployment = {
    network: 'sepolia',
    chainId: network.chainId.toString(),
    contract: 'PrivateScratchRegistry',
    address,
    deployer: deployer.address,
    deployedAt: new Date().toISOString(),
    explorer: `https://sepolia.etherscan.io/address/${address}`
  };
  fs.writeFileSync(path.join(deploymentDir, 'sepolia.json'), JSON.stringify(deployment, null, 2));

  const generatedDir = path.join(process.cwd(), 'src', 'generated');
  fs.mkdirSync(generatedDir, { recursive: true });
  fs.writeFileSync(
    path.join(generatedDir, 'deployment.ts'),
    `// Auto-generated by scripts/deploy.ts. Safe to commit.\nexport const DEPLOYMENT = ${JSON.stringify(deployment, null, 2)} as const;\n`
  );
  console.log('Wrote deployment/sepolia.json and src/generated/deployment.ts');
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
